### ISSUE TITLE
Add support for more Defaults types

### ISSUE THREAD

**Issue by haxorof** [arillso/ansible.sudoers#54]
Today this role only supports the simplest variant of the Defaults types which is limiting:
```
Default_Type ::= 'Defaults' |
                 'Defaults' '@' Host_List |
                 'Defaults' ':' User_List |
                 'Defaults' '!' Cmnd_List |
                 'Defaults' '>' Runas_List
```

Would be great to have the possibility to for example be able to generate lines like below using this role:
```
Defaults!MyCMD  env_keep+=HOME
```

**Comment by haxorof** [comment]
Just as a quick proposal the configuration could look similar to this for the Cmd_List related type:
```yaml
sudoers_sudoers:
  defaults_cmds:
    MyCMD: env_keep+=HOME
```

**Comment by kraker** [comment]
Seconded, I find myself needing this also.

**Comment by kraker** [comment]
Submitted a [PR](https://github.com/arillso/ansible.sudoers/pull/65) that addresses this issue.

**Comment by sbaerlocher** [comment]
Is implemented
